


= Brown Belt
Just like the of ripening seed that is ready for harvest, the brown color in karate belts represents that students skills are getting matured and he’s leveling up to higher expertise. So, brown belt is awarded to students whose techniques have begun to mature.



Calling features, filter for tags

env config with karate-config.js
Environment Specific Config

Gatling,
Cucumber Reports
JUnit Reports

= Black belt



Integration patterns
Become a Tester that a deeper insight about consequences of using different tools.
Knowing how to use it.. with integration usage patterns

WireMock aso.

Betrachtung von Test Driven Api Design aso.

Abschluss quote:

[quote, Mr Miyagi]
“Just remember, license never replace eye, ear, and brain.”

//

// "It's okay to lose to opponent, it's never okay to lose to fear."

// Die perspective eines Juniors müssen wir bei dem was wir schaffen im auge behalten.. 


“Never trust spiritual leader who cannot dance.” 
“If come from inside you, always right one.” 

"Walk on road, hm? Walk left side, safe. Walk right side, safe. Walk middle, sooner or later…get squish just like grape.” 
“Daniel-San, lie become truth only if person wanna believe it.”
“Wax on, wax off. Wax on, wax off.” 

“Miyagi: Oh, Daniel-san, you too much by self, not good.
Daniel: I’m not by myself, I’m with you.
Miyagi: To make honey, young bee need young flower…not old prune.”


"Daniel-San, lie become truth only if person wanna believe it."


“Daniel: You could have killed him, couldn’t you?
Mr. Miyagi: Hai.
Daniel: Well, why didn’t you?
Mr. Miyagi: Because Daniel, for man with no forgiveness in heart, life worse punishment than death.”


ok maybe this should be a thread. so here goes:
:+1:
5

